# Generated by Django 5.2.5 on 2025-12-31 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_parent_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('token_type', models.CharField(choices=[('owner', 'Owner'), ('guest', 'Guest')], default='owner', max_length=10, verbose_name='Token type')),
                ('guest_name', models.CharField(blank=True, max_length=255, verbose_name='Guest name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used at')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='bookings.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Access token',
                'verbose_name_plural': 'Access tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_type', models.CharField(choices=[('owner', 'Owner'), ('guest', 'Guest')], default='owner', max_length=10, verbose_name='Visitor type')),
                ('visitor_name', models.CharField(blank=True, help_text='For guest visits', max_length=255, verbose_name='Visitor name')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Visited at')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('access_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='visits.accesstoken', verbose_name='Access token')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='bookings.booking', verbose_name='Booking')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_visits', to=settings.AUTH_USER_MODEL, verbose_name='Scanned by')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['-visited_at'],
            },
        ),
    ]
