# Generated by Django 5.0.4 on 2026-03-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_tariffpricetier'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='storage_unit',
            field=models.ForeignKey(blank=True, help_text='Specific unit this token grants access to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_tokens', to='services.storageunit', verbose_name='Storage unit'),
        ),
    ]
