# Generated by Django 5.0.4 on 2026-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_populate_accesstoken_storage_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='location_name',
            field=models.CharField(blank=True, help_text='Snapshot of location name at time of visit', max_length=255, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='visit',
            name='scanned_by_name',
            field=models.CharField(blank=True, help_text='Snapshot of manager name at time of visit', max_length=255, verbose_name='Scanned by (name)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='unit_code',
            field=models.CharField(blank=True, help_text='Snapshot of storage unit code at time of visit', max_length=100, verbose_name='Unit code'),
        ),
    ]
