# Generated by Django 5.0.4 on 2026-03-13 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(help_text='HTML allowed', verbose_name='Content')),
                ('content_en', models.TextField(help_text='HTML allowed', null=True, verbose_name='Content')),
                ('content_ru', models.TextField(help_text='HTML allowed', null=True, verbose_name='Content')),
                ('content_ar', models.TextField(help_text='HTML allowed', null=True, verbose_name='Content')),
                ('is_required', models.BooleanField(default=False, help_text='User must accept before booking', verbose_name='Required for booking')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PolicyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='policies.policy', verbose_name='Policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_consents', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Policy consent',
                'verbose_name_plural': 'Policy consents',
                'unique_together': {('user', 'policy')},
            },
        ),
    ]
