# Generated by Django 5.0.4 on 2026-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='consent_label',
            field=models.CharField(blank=True, default='', help_text='Checkbox text, e.g. "I have read and accept the Terms of Service"', max_length=500, verbose_name='Consent label'),
        ),
        migrations.AddField(
            model_name='policy',
            name='consent_label_ar',
            field=models.CharField(blank=True, default='', help_text='Checkbox text, e.g. "I have read and accept the Terms of Service"', max_length=500, null=True, verbose_name='Consent label'),
        ),
        migrations.AddField(
            model_name='policy',
            name='consent_label_en',
            field=models.CharField(blank=True, default='', help_text='Checkbox text, e.g. "I have read and accept the Terms of Service"', max_length=500, null=True, verbose_name='Consent label'),
        ),
        migrations.AddField(
            model_name='policy',
            name='consent_label_ru',
            field=models.CharField(blank=True, default='', help_text='Checkbox text, e.g. "I have read and accept the Terms of Service"', max_length=500, null=True, verbose_name='Consent label'),
        ),
    ]
