# Generated by Django 5.2.5 on 2026-03-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policy_consent_label_policy_consent_label_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='consent_label',
            field=models.CharField(blank=True, default='', help_text='Use {link} for auto-link to policy, e.g. "I have read and accept the {link}"', max_length=500, verbose_name='Consent label'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='consent_label_ar',
            field=models.CharField(blank=True, default='', help_text='Use {link} for auto-link to policy, e.g. "I have read and accept the {link}"', max_length=500, null=True, verbose_name='Consent label'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='consent_label_en',
            field=models.CharField(blank=True, default='', help_text='Use {link} for auto-link to policy, e.g. "I have read and accept the {link}"', max_length=500, null=True, verbose_name='Consent label'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='consent_label_ru',
            field=models.CharField(blank=True, default='', help_text='Use {link} for auto-link to policy, e.g. "I have read and accept the {link}"', max_length=500, null=True, verbose_name='Consent label'),
        ),
    ]
