# Generated by Django 5.0.4 on 2026-03-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_line1', models.CharField(help_text='e.g. "Secure Car"', max_length=255, verbose_name='Hero title (line 1)')),
                ('hero_title_line1_en', models.CharField(help_text='e.g. "Secure Car"', max_length=255, null=True, verbose_name='Hero title (line 1)')),
                ('hero_title_line1_ru', models.CharField(help_text='e.g. "Secure Car"', max_length=255, null=True, verbose_name='Hero title (line 1)')),
                ('hero_title_line1_ar', models.CharField(help_text='e.g. "Secure Car"', max_length=255, null=True, verbose_name='Hero title (line 1)')),
                ('hero_title_line2', models.CharField(help_text='e.g. "Storage in Dubai"', max_length=255, verbose_name='Hero title (line 2)')),
                ('hero_title_line2_en', models.CharField(help_text='e.g. "Storage in Dubai"', max_length=255, null=True, verbose_name='Hero title (line 2)')),
                ('hero_title_line2_ru', models.CharField(help_text='e.g. "Storage in Dubai"', max_length=255, null=True, verbose_name='Hero title (line 2)')),
                ('hero_title_line2_ar', models.CharField(help_text='e.g. "Storage in Dubai"', max_length=255, null=True, verbose_name='Hero title (line 2)')),
                ('hero_subtitle', models.TextField(help_text='Text below the title', verbose_name='Hero subtitle')),
                ('hero_subtitle_en', models.TextField(help_text='Text below the title', null=True, verbose_name='Hero subtitle')),
                ('hero_subtitle_ru', models.TextField(help_text='Text below the title', null=True, verbose_name='Hero subtitle')),
                ('hero_subtitle_ar', models.TextField(help_text='Text below the title', null=True, verbose_name='Hero subtitle')),
                ('hero_cta_primary_text', models.CharField(help_text='e.g. "Reserve your spot"', max_length=100, verbose_name='Primary button text')),
                ('hero_cta_primary_text_en', models.CharField(help_text='e.g. "Reserve your spot"', max_length=100, null=True, verbose_name='Primary button text')),
                ('hero_cta_primary_text_ru', models.CharField(help_text='e.g. "Reserve your spot"', max_length=100, null=True, verbose_name='Primary button text')),
                ('hero_cta_primary_text_ar', models.CharField(help_text='e.g. "Reserve your spot"', max_length=100, null=True, verbose_name='Primary button text')),
                ('hero_cta_primary_url', models.CharField(blank=True, help_text='Leave blank to use default tariff link', max_length=255, verbose_name='Primary button URL')),
                ('hero_cta_secondary_text', models.CharField(help_text='e.g. "Show locations"', max_length=100, verbose_name='Secondary button text')),
                ('hero_cta_secondary_text_en', models.CharField(help_text='e.g. "Show locations"', max_length=100, null=True, verbose_name='Secondary button text')),
                ('hero_cta_secondary_text_ru', models.CharField(help_text='e.g. "Show locations"', max_length=100, null=True, verbose_name='Secondary button text')),
                ('hero_cta_secondary_text_ar', models.CharField(help_text='e.g. "Show locations"', max_length=100, null=True, verbose_name='Secondary button text')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
    ]
