# Generated by Django 5.0.4 on 2026-03-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_title_line3',
            field=models.CharField(default='', help_text='e.g. "in Dubai"', max_length=255, verbose_name='Hero title (after logo)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_line3_ar',
            field=models.CharField(default='', help_text='e.g. "in Dubai"', max_length=255, null=True, verbose_name='Hero title (after logo)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_line3_en',
            field=models.CharField(default='', help_text='e.g. "in Dubai"', max_length=255, null=True, verbose_name='Hero title (after logo)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_line3_ru',
            field=models.CharField(default='', help_text='e.g. "in Dubai"', max_length=255, null=True, verbose_name='Hero title (after logo)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title_line2',
            field=models.CharField(help_text='e.g. "Storage"', max_length=255, verbose_name='Hero title (before logo)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title_line2_ar',
            field=models.CharField(help_text='e.g. "Storage"', max_length=255, null=True, verbose_name='Hero title (before logo)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title_line2_en',
            field=models.CharField(help_text='e.g. "Storage"', max_length=255, null=True, verbose_name='Hero title (before logo)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title_line2_ru',
            field=models.CharField(help_text='e.g. "Storage"', max_length=255, null=True, verbose_name='Hero title (before logo)'),
        ),
    ]
