# Generated by Django 5.0.4 on 2026-03-05 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homepage_hero_title_line3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='benefits_cta_text',
            field=models.CharField(default='', help_text='e.g. "Reserve your spot"', max_length=100, verbose_name='Benefits button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_cta_text_ar',
            field=models.CharField(default='', help_text='e.g. "Reserve your spot"', max_length=100, null=True, verbose_name='Benefits button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_cta_text_en',
            field=models.CharField(default='', help_text='e.g. "Reserve your spot"', max_length=100, null=True, verbose_name='Benefits button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_cta_text_ru',
            field=models.CharField(default='', help_text='e.g. "Reserve your spot"', max_length=100, null=True, verbose_name='Benefits button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_subtitle',
            field=models.TextField(blank=True, default='', help_text='HTML allowed', verbose_name='Benefits subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_subtitle_ar',
            field=models.TextField(blank=True, default='', help_text='HTML allowed', null=True, verbose_name='Benefits subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_subtitle_en',
            field=models.TextField(blank=True, default='', help_text='HTML allowed', null=True, verbose_name='Benefits subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_subtitle_ru',
            field=models.TextField(blank=True, default='', help_text='HTML allowed', null=True, verbose_name='Benefits subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_title',
            field=models.CharField(default='', help_text='e.g. "Free up space"', max_length=255, verbose_name='Benefits title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_title_ar',
            field=models.CharField(default='', help_text='e.g. "Free up space"', max_length=255, null=True, verbose_name='Benefits title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_title_en',
            field=models.CharField(default='', help_text='e.g. "Free up space"', max_length=255, null=True, verbose_name='Benefits title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_title_ru',
            field=models.CharField(default='', help_text='e.g. "Free up space"', max_length=255, null=True, verbose_name='Benefits title'),
        ),
        migrations.CreateModel(
            name='HomeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('description_en', models.CharField(max_length=500, null=True, verbose_name='Description')),
                ('description_ru', models.CharField(max_length=500, null=True, verbose_name='Description')),
                ('description_ar', models.CharField(max_length=500, null=True, verbose_name='Description')),
                ('svg_icon', models.TextField(blank=True, help_text='Full SVG code', verbose_name='SVG icon')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='pages.homepage', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'ordering': ['sort_order'],
            },
        ),
    ]
