# Generated by Django 5.0.4 on 2026-03-05 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_homepage_benefits_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='gallery_subtitle',
            field=models.TextField(blank=True, default='', verbose_name='Gallery subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_subtitle_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Gallery subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_subtitle_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Gallery subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_subtitle_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Gallery subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_title',
            field=models.CharField(default='', max_length=255, verbose_name='Gallery title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_title_ar',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Gallery title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_title_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Gallery title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_title_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Gallery title'),
        ),
        migrations.CreateModel(
            name='HomeGallerySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/gallery/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt text')),
                ('alt_text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text')),
                ('alt_text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text')),
                ('alt_text_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('caption_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('caption_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_slides', to='pages.homepage', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Gallery slide',
                'verbose_name_plural': 'Gallery slides',
                'ordering': ['sort_order'],
            },
        ),
    ]
