# Generated by Django 5.0.4 on 2026-03-05 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_homepage_gallery_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='dashboard_subtitle',
            field=models.TextField(blank=True, default='', help_text='HTML allowed', verbose_name='Dashboard subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='dashboard_subtitle_ar',
            field=models.TextField(blank=True, default='', help_text='HTML allowed', null=True, verbose_name='Dashboard subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='dashboard_subtitle_en',
            field=models.TextField(blank=True, default='', help_text='HTML allowed', null=True, verbose_name='Dashboard subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='dashboard_subtitle_ru',
            field=models.TextField(blank=True, default='', help_text='HTML allowed', null=True, verbose_name='Dashboard subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='dashboard_title',
            field=models.CharField(default='', max_length=255, verbose_name='Dashboard title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='dashboard_title_ar',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Dashboard title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='dashboard_title_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Dashboard title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='dashboard_title_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Dashboard title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feedback_cta_text',
            field=models.CharField(default='', max_length=100, verbose_name='Feedback button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feedback_cta_text_ar',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Feedback button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feedback_cta_text_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Feedback button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feedback_cta_text_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Feedback button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feedback_title',
            field=models.TextField(default='', help_text='HTML allowed', verbose_name='Feedback title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feedback_title_ar',
            field=models.TextField(default='', help_text='HTML allowed', null=True, verbose_name='Feedback title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feedback_title_en',
            field=models.TextField(default='', help_text='HTML allowed', null=True, verbose_name='Feedback title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feedback_title_ru',
            field=models.TextField(default='', help_text='HTML allowed', null=True, verbose_name='Feedback title'),
        ),
        migrations.CreateModel(
            name='HomeDashboardFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Text')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Text')),
                ('text_ru', models.CharField(max_length=500, null=True, verbose_name='Text')),
                ('text_ar', models.CharField(max_length=500, null=True, verbose_name='Text')),
                ('svg_icon', models.TextField(blank=True, help_text='Full SVG code', verbose_name='SVG icon')),
                ('bg_color', models.CharField(choices=[('bg-blue-600', 'Blue'), ('bg-orange-500', 'Orange'), ('bg-black', 'Black')], default='bg-blue-600', max_length=50, verbose_name='Background color')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_features', to='pages.homepage', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Dashboard feature',
                'verbose_name_plural': 'Dashboard features',
                'ordering': ['sort_order'],
            },
        ),
    ]
