# Generated by Django 5.0.4 on 2026-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homepage_dashboard_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', help_text='HTML allowed', verbose_name='Feedback title')),
                ('title_en', models.TextField(default='', help_text='HTML allowed', null=True, verbose_name='Feedback title')),
                ('title_ru', models.TextField(default='', help_text='HTML allowed', null=True, verbose_name='Feedback title')),
                ('title_ar', models.TextField(default='', help_text='HTML allowed', null=True, verbose_name='Feedback title')),
                ('cta_text', models.CharField(default='', max_length=100, verbose_name='Button text')),
                ('cta_text_en', models.CharField(default='', max_length=100, null=True, verbose_name='Button text')),
                ('cta_text_ru', models.CharField(default='', max_length=100, null=True, verbose_name='Button text')),
                ('cta_text_ar', models.CharField(default='', max_length=100, null=True, verbose_name='Button text')),
            ],
            options={
                'verbose_name': 'Feedback CTA',
                'verbose_name_plural': 'Feedback CTA',
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feedback_cta_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feedback_cta_text_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feedback_cta_text_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feedback_cta_text_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feedback_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feedback_title_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feedback_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feedback_title_ru',
        ),
    ]
