# Generated by Django 5.0.4 on 2026-03-05 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_feedbackcta_remove_homepage_feedback_cta_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='About', max_length=100, verbose_name='Hero sidebar label')),
                ('hero_label_en', models.CharField(default='About', max_length=100, null=True, verbose_name='Hero sidebar label')),
                ('hero_label_ru', models.CharField(default='About', max_length=100, null=True, verbose_name='Hero sidebar label')),
                ('hero_label_ar', models.CharField(default='About', max_length=100, null=True, verbose_name='Hero sidebar label')),
                ('hero_title', models.CharField(default='', help_text='e.g. "A&M Foxbox"', max_length=255, verbose_name='Hero title')),
                ('hero_title_en', models.CharField(default='', help_text='e.g. "A&M Foxbox"', max_length=255, null=True, verbose_name='Hero title')),
                ('hero_title_ru', models.CharField(default='', help_text='e.g. "A&M Foxbox"', max_length=255, null=True, verbose_name='Hero title')),
                ('hero_title_ar', models.CharField(default='', help_text='e.g. "A&M Foxbox"', max_length=255, null=True, verbose_name='Hero title')),
                ('hero_subtitle', models.TextField(default='', help_text='HTML allowed, orange text', verbose_name='Hero subtitle')),
                ('hero_subtitle_en', models.TextField(default='', help_text='HTML allowed, orange text', null=True, verbose_name='Hero subtitle')),
                ('hero_subtitle_ru', models.TextField(default='', help_text='HTML allowed, orange text', null=True, verbose_name='Hero subtitle')),
                ('hero_subtitle_ar', models.TextField(default='', help_text='HTML allowed, orange text', null=True, verbose_name='Hero subtitle')),
                ('hero_block_title', models.CharField(default='', help_text='e.g. "What we offer"', max_length=255, verbose_name='Hero block title')),
                ('hero_block_title_en', models.CharField(default='', help_text='e.g. "What we offer"', max_length=255, null=True, verbose_name='Hero block title')),
                ('hero_block_title_ru', models.CharField(default='', help_text='e.g. "What we offer"', max_length=255, null=True, verbose_name='Hero block title')),
                ('hero_block_title_ar', models.CharField(default='', help_text='e.g. "What we offer"', max_length=255, null=True, verbose_name='Hero block title')),
                ('hero_block_text', models.TextField(default='', verbose_name='Hero block text')),
                ('hero_block_text_en', models.TextField(default='', null=True, verbose_name='Hero block text')),
                ('hero_block_text_ru', models.TextField(default='', null=True, verbose_name='Hero block text')),
                ('hero_block_text_ar', models.TextField(default='', null=True, verbose_name='Hero block text')),
                ('hero_image', models.ImageField(blank=True, upload_to='pages/about/', verbose_name='Hero image')),
                ('hero_image_alt', models.CharField(default='foxbox', max_length=255, verbose_name='Hero image alt text')),
                ('hero_image_alt_en', models.CharField(default='foxbox', max_length=255, null=True, verbose_name='Hero image alt text')),
                ('hero_image_alt_ru', models.CharField(default='foxbox', max_length=255, null=True, verbose_name='Hero image alt text')),
                ('hero_image_alt_ar', models.CharField(default='foxbox', max_length=255, null=True, verbose_name='Hero image alt text')),
                ('offers_label', models.CharField(default='Offers', max_length=100, verbose_name='Offers sidebar label')),
                ('offers_label_en', models.CharField(default='Offers', max_length=100, null=True, verbose_name='Offers sidebar label')),
                ('offers_label_ru', models.CharField(default='Offers', max_length=100, null=True, verbose_name='Offers sidebar label')),
                ('offers_label_ar', models.CharField(default='Offers', max_length=100, null=True, verbose_name='Offers sidebar label')),
                ('offers_title', models.CharField(default='', max_length=255, verbose_name='Offers title')),
                ('offers_title_en', models.CharField(default='', max_length=255, null=True, verbose_name='Offers title')),
                ('offers_title_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Offers title')),
                ('offers_title_ar', models.CharField(default='', max_length=255, null=True, verbose_name='Offers title')),
                ('offers_description', models.TextField(default='', verbose_name='Offers description')),
                ('offers_description_en', models.TextField(default='', null=True, verbose_name='Offers description')),
                ('offers_description_ru', models.TextField(default='', null=True, verbose_name='Offers description')),
                ('offers_description_ar', models.TextField(default='', null=True, verbose_name='Offers description')),
                ('offers_text', models.TextField(default='', help_text='Text above the list', verbose_name='Offers text')),
                ('offers_text_en', models.TextField(default='', help_text='Text above the list', null=True, verbose_name='Offers text')),
                ('offers_text_ru', models.TextField(default='', help_text='Text above the list', null=True, verbose_name='Offers text')),
                ('offers_text_ar', models.TextField(default='', help_text='Text above the list', null=True, verbose_name='Offers text')),
                ('offers_closing', models.TextField(default='', help_text='Bold text below the list', verbose_name='Offers closing text')),
                ('offers_closing_en', models.TextField(default='', help_text='Bold text below the list', null=True, verbose_name='Offers closing text')),
                ('offers_closing_ru', models.TextField(default='', help_text='Bold text below the list', null=True, verbose_name='Offers closing text')),
                ('offers_closing_ar', models.TextField(default='', help_text='Bold text below the list', null=True, verbose_name='Offers closing text')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='AboutOfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('text_en', models.CharField(max_length=255, null=True, verbose_name='Text')),
                ('text_ru', models.CharField(max_length=255, null=True, verbose_name='Text')),
                ('text_ar', models.CharField(max_length=255, null=True, verbose_name='Text')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='pages.aboutpage', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Offer item',
                'verbose_name_plural': 'Offer items',
                'ordering': ['sort_order'],
            },
        ),
    ]
