# Generated by Django 5.0.4 on 2026-03-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_aboutpage_aboutofferitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Contact', max_length=100, verbose_name='Hero sidebar label')),
                ('hero_label_en', models.CharField(default='Contact', max_length=100, null=True, verbose_name='Hero sidebar label')),
                ('hero_label_ru', models.CharField(default='Contact', max_length=100, null=True, verbose_name='Hero sidebar label')),
                ('hero_label_ar', models.CharField(default='Contact', max_length=100, null=True, verbose_name='Hero sidebar label')),
                ('hero_title', models.CharField(default='', max_length=255, verbose_name='Hero title')),
                ('hero_title_en', models.CharField(default='', max_length=255, null=True, verbose_name='Hero title')),
                ('hero_title_ru', models.CharField(default='', max_length=255, null=True, verbose_name='Hero title')),
                ('hero_title_ar', models.CharField(default='', max_length=255, null=True, verbose_name='Hero title')),
                ('hero_subtitle', models.TextField(default='', verbose_name='Hero subtitle')),
                ('hero_subtitle_en', models.TextField(default='', null=True, verbose_name='Hero subtitle')),
                ('hero_subtitle_ru', models.TextField(default='', null=True, verbose_name='Hero subtitle')),
                ('hero_subtitle_ar', models.TextField(default='', null=True, verbose_name='Hero subtitle')),
            ],
            options={
                'verbose_name': 'Contacts Page',
                'verbose_name_plural': 'Contacts Page',
            },
        ),
        migrations.CreateModel(
            name='ContactInfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('label_en', models.CharField(max_length=255, null=True, verbose_name='Label')),
                ('label_ru', models.CharField(max_length=255, null=True, verbose_name='Label')),
                ('label_ar', models.CharField(max_length=255, null=True, verbose_name='Label')),
                ('value', models.TextField(verbose_name='Value')),
                ('value_en', models.TextField(null=True, verbose_name='Value')),
                ('value_ru', models.TextField(null=True, verbose_name='Value')),
                ('value_ar', models.TextField(null=True, verbose_name='Value')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_items', to='pages.contactspage', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Info item',
                'verbose_name_plural': 'Info items',
                'ordering': ['sort_order'],
            },
        ),
    ]
