# Generated by Django 5.0.4 on 2026-03-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('url', models.CharField(help_text='e.g. / or /services/auto/standard/ or https://example.com', max_length=500, verbose_name='URL')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Open in new tab')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Navigation link',
                'verbose_name_plural': 'Navigation links',
                'ordering': ['sort_order'],
            },
        ),
    ]
