# Generated by Django 5.0.4 on 2026-03-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_populate_nav_links'),
    ]

    operations = [
        # Rename url -> custom_url (preserves data)
        migrations.RenameField(
            model_name='navlink',
            old_name='url',
            new_name='custom_url',
        ),
        migrations.AlterField(
            model_name='navlink',
            name='custom_url',
            field=models.CharField(blank=True, default='', help_text='Only for "Custom URL" page type, e.g. /services/auto/standard/', max_length=500, verbose_name='Custom URL'),
        ),
        migrations.AddField(
            model_name='navlink',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contacts', 'Contacts'), ('custom', 'Custom URL')], default='custom', max_length=50, verbose_name='Page'),
        ),
    ]
