# Generated by Django 5.0.4 on 2026-03-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_convert_navlink_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegalleryslide',
            name='slide_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10, verbose_name='Slide type'),
        ),
        migrations.AddField(
            model_name='homegalleryslide',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 video file. Used when slide type is "Video".', upload_to='pages/gallery/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='homegalleryslide',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages/gallery/', verbose_name='Image'),
        ),
    ]
