# Generated by Django 5.2.5 on 2025-12-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariffperiod',
            options={'ordering': ['sort_order', 'duration_value'], 'verbose_name': 'Tariff period', 'verbose_name_plural': 'Tariff periods'},
        ),
        migrations.RemoveField(
            model_name='tariffperiod',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='tariffperiod',
            name='duration_type',
            field=models.CharField(choices=[('days', 'Days'), ('months', 'Months')], default='months', max_length=10, verbose_name='Duration type'),
        ),
        migrations.AddField(
            model_name='tariffperiod',
            name='duration_value',
            field=models.PositiveIntegerField(default=1, help_text='Number of days or months', verbose_name='Duration value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariffperiod',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Custom period'),
        ),
    ]
