# Generated by Django 5.2.5 on 2025-12-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_location_type'),
        ('services', '0002_alter_tariffperiod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from English name', max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('service', 'location', 'slug')},
        ),
    ]
