# Generated by Django 5.2.5 on 2025-12-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_tariff_slug_alter_tariff_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffperiod',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Pre-selected by default on frontend', verbose_name='Recommended'),
        ),
    ]
