# Generated by Django 5.2.5 on 2025-12-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_tariffperiod_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='deposit_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deposit (AED)'),
        ),
    ]
