# Generated by Django 5.0.4 on 2026-03-13 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_tariff_deposit_aed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_units', models.PositiveIntegerField(help_text='Minimum number of units for this price tier (inclusive)', verbose_name='Minimum units')),
                ('max_units', models.PositiveIntegerField(blank=True, help_text='Maximum number of units (inclusive). Leave blank for unlimited.', null=True, verbose_name='Maximum units')),
                ('price_per_unit_aed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per unit (AED)')),
                ('price_per_unit_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per unit (USD)')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='services.tariffperiod', verbose_name='Period')),
            ],
            options={
                'verbose_name': 'Price tier',
                'verbose_name_plural': 'Price tiers',
                'ordering': ['min_units'],
                'unique_together': {('period', 'min_units')},
            },
        ),
    ]
