# Generated by Django 5.0.4 on 2026-03-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_populate_default_tiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffperiod',
            name='original_price_aed',
        ),
        migrations.RemoveField(
            model_name='tariffperiod',
            name='original_price_usd',
        ),
        migrations.RemoveField(
            model_name='tariffperiod',
            name='price_aed',
        ),
        migrations.RemoveField(
            model_name='tariffperiod',
            name='price_usd',
        ),
        migrations.RemoveField(
            model_name='tariffpricetier',
            name='price_per_unit_usd',
        ),
        migrations.AddField(
            model_name='tariffpricetier',
            name='original_price_per_unit_aed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For displaying discount. Leave blank if no discount.', max_digits=10, null=True, verbose_name='Original price per unit (AED)'),
        ),
    ]
