# Generated by Django 5.0.4 on 2026-03-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_legacy_price_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffperiod',
            name='discount_label',
        ),
        migrations.RemoveField(
            model_name='tariffperiod',
            name='discount_label_ar',
        ),
        migrations.RemoveField(
            model_name='tariffperiod',
            name='discount_label_en',
        ),
        migrations.RemoveField(
            model_name='tariffperiod',
            name='discount_label_ru',
        ),
    ]
