# Generated by Django 5.0.4 on 2026-03-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_discount_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quantity_label',
            field=models.CharField(blank=True, default='', help_text='Label for the quantity selector, e.g. "Number of cars" or "Number of units"', max_length=255, verbose_name='Quantity label'),
        ),
        migrations.AddField(
            model_name='service',
            name='quantity_label_ar',
            field=models.CharField(blank=True, default='', help_text='Label for the quantity selector, e.g. "Number of cars" or "Number of units"', max_length=255, null=True, verbose_name='Quantity label'),
        ),
        migrations.AddField(
            model_name='service',
            name='quantity_label_en',
            field=models.CharField(blank=True, default='', help_text='Label for the quantity selector, e.g. "Number of cars" or "Number of units"', max_length=255, null=True, verbose_name='Quantity label'),
        ),
        migrations.AddField(
            model_name='service',
            name='quantity_label_ru',
            field=models.CharField(blank=True, default='', help_text='Label for the quantity selector, e.g. "Number of cars" or "Number of units"', max_length=255, null=True, verbose_name='Quantity label'),
        ),
    ]
