# Generated by Django 5.0.4 on 2026-03-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_quantity_label_service_quantity_label_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='addons_label',
            field=models.CharField(blank=True, default='', help_text='Label for additional services section, e.g. "Additional services"', max_length=255, verbose_name='Addons label'),
        ),
        migrations.AddField(
            model_name='service',
            name='addons_label_ar',
            field=models.CharField(blank=True, default='', help_text='Label for additional services section, e.g. "Additional services"', max_length=255, null=True, verbose_name='Addons label'),
        ),
        migrations.AddField(
            model_name='service',
            name='addons_label_en',
            field=models.CharField(blank=True, default='', help_text='Label for additional services section, e.g. "Additional services"', max_length=255, null=True, verbose_name='Addons label'),
        ),
        migrations.AddField(
            model_name='service',
            name='addons_label_ru',
            field=models.CharField(blank=True, default='', help_text='Label for additional services section, e.g. "Additional services"', max_length=255, null=True, verbose_name='Addons label'),
        ),
    ]
