# Generated by Django 5.2.5 on 2025-12-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID card'),
        ),
    ]
