# Generated by Django 5.2.5 on 2025-12-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_telegramlinktoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that ID card already exists.'}, max_length=50, null=True, unique=True, verbose_name='ID card'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
    ]
