# Generated by Django 5.2.5 on 2025-12-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('street_en', models.CharField(max_length=255, null=True, verbose_name='street')),
                ('street_ru', models.CharField(max_length=255, null=True, verbose_name='street')),
                ('street_ar', models.CharField(max_length=255, null=True, verbose_name='street')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='description')),
                ('working_hours', models.CharField(help_text='e.g. Sun-Thu 9:00-18:00', max_length=255, verbose_name='working hours')),
                ('working_hours_en', models.CharField(help_text='e.g. Sun-Thu 9:00-18:00', max_length=255, null=True, verbose_name='working hours')),
                ('working_hours_ru', models.CharField(help_text='e.g. Sun-Thu 9:00-18:00', max_length=255, null=True, verbose_name='working hours')),
                ('working_hours_ar', models.CharField(help_text='e.g. Sun-Thu 9:00-18:00', max_length=255, null=True, verbose_name='working hours')),
                ('building', models.CharField(max_length=50, verbose_name='building')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
