# Generated by Django 5.2.5 on 2025-12-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='building_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='building'),
        ),
        migrations.AddField(
            model_name='location',
            name='building_en',
            field=models.CharField(max_length=50, null=True, verbose_name='building'),
        ),
        migrations.AddField(
            model_name='location',
            name='building_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='building'),
        ),
    ]
