# Generated by Django 5.2.5 on 2025-12-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_building_ar_location_building_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('auto', 'Auto storage'), ('storage', 'Storage')], default='storage', max_length=20, verbose_name='location type'),
        ),
    ]
