# Generated by Django 5.2.5 on 2025-12-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('auto', 'Auto storage'), ('storage', 'Storage'), ('headoffice', 'Head office')], default='storage', max_length=20, verbose_name='location type'),
        ),
    ]
