# Generated by Django 5.2.5 on 2025-12-30 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0005_tariff_deposit_aed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('price_aed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Period price (AED)')),
                ('addons_aed', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Addons price (AED)')),
                ('deposit_aed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deposit (AED)')),
                ('total_aed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (AED)')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe session ID')),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe payment ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Booking cancelled if not paid before this time', verbose_name='Payment expires at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.tariffperiod', verbose_name='Period')),
                ('storage_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.storageunit', verbose_name='Storage unit')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.tariff', verbose_name='Tariff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_aed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (AED)')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_addons', to='services.addonservice', verbose_name='Addon service')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_addons', to='bookings.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Booking addon',
                'verbose_name_plural': 'Booking addons',
            },
        ),
    ]
