# Generated by Django 5.0.4 on 2026-03-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
        ('services', '0006_tariffpricetier'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of storage units booked', verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='booking',
            name='unit_price_aed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-unit price at time of booking', max_digits=10, null=True, verbose_name='Unit price (AED)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_aed',
            field=models.DecimalField(decimal_places=2, help_text='Total storage cost: unit_price * quantity', max_digits=10, verbose_name='Period price (AED)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='storage_unit',
            field=models.ForeignKey(blank=True, help_text='Primary storage unit (for backward compatibility)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.storageunit', verbose_name='Storage unit'),
        ),
        migrations.CreateModel(
            name='BookingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_units', to='bookings.booking', verbose_name='Booking')),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_unit_entries', to='services.storageunit', verbose_name='Storage unit')),
            ],
            options={
                'verbose_name': 'Booking unit',
                'verbose_name_plural': 'Booking units',
                'unique_together': {('booking', 'storage_unit')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='storage_units',
            field=models.ManyToManyField(blank=True, related_name='bookings_multi', through='bookings.BookingUnit', to='services.storageunit', verbose_name='Storage units'),
        ),
    ]
