# Generated by Django 5.0.4 on 2026-03-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_populate_booking_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location_name',
            field=models.CharField(blank=True, help_text='Snapshot of location name at time of booking', max_length=255, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='period_label',
            field=models.CharField(blank=True, help_text='e.g. "3 months", "30 days"', max_length=100, verbose_name='Period label'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_name',
            field=models.CharField(blank=True, help_text='Snapshot of service name at time of booking', max_length=255, verbose_name='Service name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tariff_name',
            field=models.CharField(blank=True, help_text='Snapshot of tariff name at time of booking', max_length=255, verbose_name='Tariff name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='unit_codes',
            field=models.CharField(blank=True, help_text='Comma-separated unit codes at time of booking', max_length=500, verbose_name='Unit codes'),
        ),
    ]
