# Generated by Django 5.2.5 on 2026-03-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_populate_booking_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manager_notes',
            field=models.TextField(blank=True, help_text='Internal notes (refunds, reassign reasons, etc.)', verbose_name='Manager notes'),
        ),
    ]
