# Generated by Django 5.0.4 on 2026-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_add_manager_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_receipt_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Stripe receipt URL'),
        ),
    ]
