# Generated by Django 5.0.4 on 2026-03-14 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_add_stripe_receipt_url'),
        ('services', '0011_service_addons_label_service_addons_label_ar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'end_date'], name='idx_booking_status_end'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'parent_booking'], name='idx_booking_status_parent'),
        ),
    ]
