# Generated by Django 5.2.5 on 2025-12-31 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_paid', 'Booking Paid'), ('booking_expiring', 'Booking Expiring Soon'), ('booking_expired', 'Booking Expired'), ('booking_extended', 'Booking Extended'), ('visit_logged', 'Visit Logged'), ('guest_visit', 'Guest Visit'), ('welcome', 'Welcome'), ('password_changed', 'Password Changed'), ('feedback_received', 'Feedback Received')], max_length=50, verbose_name='Type')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], default='email', max_length=20, verbose_name='Channel')),
                ('email_subject', models.CharField(blank=True, max_length=255, verbose_name='Email Subject')),
                ('email_body', models.TextField(blank=True, verbose_name='Email Body')),
                ('telegram_message', models.TextField(blank=True, verbose_name='Telegram Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_paid', 'Booking Paid'), ('booking_expiring', 'Booking Expiring Soon'), ('booking_expired', 'Booking Expired'), ('booking_extended', 'Booking Extended'), ('visit_logged', 'Visit Logged'), ('guest_visit', 'Guest Visit'), ('welcome', 'Welcome'), ('password_changed', 'Password Changed'), ('feedback_received', 'Feedback Received')], max_length=50, verbose_name='Type')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], max_length=20, verbose_name='Channel')),
                ('recipient', models.CharField(max_length=255, verbose_name='Recipient')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
